In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
df=pd.read_csv(r"C:\Users\PAVAN G\Downloads\archive (1)\IMDB top 1000.csv")
df

,Unnamed: 0,Title,Certificate,Duration,Genre,Rate,Metascore,Description,Cast,Info
0,0,1. The Shawshank Redemption (1994),R,142 min,Drama,9.3,80.0,Two imprisoned men bond over a number of years...,"Director: Frank Darabont | Stars: Tim Robbins,...","Votes: 2,295,987 | Gross: $28.34M"
1,1,2. The Godfather (1972),R,175 min,"Crime, Drama",9.2,100.0,The aging patriarch of an organized crime dyna...,Director: Francis Ford Coppola | Stars: Marlon...,"Votes: 1,584,782 | Gross: $134.97M"
2,2,3. The Dark Knight (2008),PG-13,152 min,"Action, Crime, Drama",9.0,84.0,When the menace known as the Joker wreaks havo...,Director: Christopher Nolan | Stars: Christian...,"Votes: 2,260,649 | Gross: $534.86M"
3,3,4. The Godfather: Part II (1974),R,202 min,"Crime, Drama",9.0,90.0,The early life and career of Vito Corleone in ...,Director: Francis Ford Coppola | Stars: Al Pac...,"Votes: 1,107,253 | Gross: $57.30M"
4,4,5. The Lord of the Rings: The Return of the Ki...,PG-13,201 min,"Action, Adventure, Drama",8.9,94.0,Gandalf and Aragorn lead the World of Men agai...,"Director: Peter Jackson | Stars: Elijah Wood, ...","Votes: 1,614,369 | Gross: $377.85M"
...,...,...,...,...,...,...,...,...,...,...
995,995,398. Scent of a Woman (1992),R,156 min,Drama,8.0,NaN,A prep school student needing money agrees to ...,"Director: Martin Brest | Stars: Al Pacino, Chr...","Votes: 256,515 | Gross: $63.90M"
996,996,399. Aladdin (1992),G,90 min,"Animation, Adventure, Comedy",8.0,86.0,A kindhearted street urchin and a power-hungry...,"Directors: Ron Clements, John Musker | Stars: ...","Votes: 367,489 | Gross: $217.35M"
997,997,400. JFK (1991),R,189 min,"Drama, History, Thriller",8.0,72.0,New Orleans District Attorney Jim Garrison dis...,"Director: Oliver Stone | Stars: Kevin Costner,...","Votes: 139,634 | Gross: $70.41M"
998,998,301. Nights of Cabiria (1957),Not Rated,110 min,Drama,8.1,NaN,A waifish prostitute wanders the streets of Ro...,Director: Federico Fellini | Stars: Giulietta ...,"Votes: 42,160 | Gross: $0.75M"
999,999,302. Throne of Blood (1957),Not Rated,110 min,"Drama, History",8.1,NaN,"A war-hardened general, egged on by his ambiti...",Director: Akira Kurosawa | Stars: Toshirô Mifu...,"Votes: 45,579"

In [21]:
df.head(10)

,Unnamed: 0,Title,Certificate,Duration,Genre,Rate,Metascore,Description,Cast,Info
0,0,1. The Shawshank Redemption (1994),R,142 min,Drama,9.3,80.0,Two imprisoned men bond over a number of years...,"Director: Frank Darabont | Stars: Tim Robbins,...","Votes: 2,295,987 | Gross: $28.34M"
1,1,2. The Godfather (1972),R,175 min,"Crime, Drama",9.2,100.0,The aging patriarch of an organized crime dyna...,Director: Francis Ford Coppola | Stars: Marlon...,"Votes: 1,584,782 | Gross: $134.97M"
2,2,3. The Dark Knight (2008),PG-13,152 min,"Action, Crime, Drama",9.0,84.0,When the menace known as the Joker wreaks havo...,Director: Christopher Nolan | Stars: Christian...,"Votes: 2,260,649 | Gross: $534.86M"
3,3,4. The Godfather: Part II (1974),R,202 min,"Crime, Drama",9.0,90.0,The early life and career of Vito Corleone in ...,Director: Francis Ford Coppola | Stars: Al Pac...,"Votes: 1,107,253 | Gross: $57.30M"
4,4,5. The Lord of the Rings: The Return of the Ki...,PG-13,201 min,"Action, Adventure, Drama",8.9,94.0,Gandalf and Aragorn lead the World of Men agai...,"Director: Peter Jackson | Stars: Elijah Wood, ...","Votes: 1,614,369 | Gross: $377.85M"
5,5,6. Pulp Fiction (1994),R,154 min,"Crime, Drama",8.9,94.0,"The lives of two mob hitmen, a boxer, a gangst...",Director: Quentin Tarantino | Stars: John Trav...,"Votes: 1,792,919 | Gross: $107.93M"
6,6,7. Schindler's List (1993),R,195 min,"Biography, Drama, History",8.9,94.0,"In German-occupied Poland during World War II,...",Director: Steven Spielberg | Stars: Liam Neeso...,"Votes: 1,191,793 | Gross: $96.90M"
7,7,8. 12 Angry Men (1957),Approved,96 min,"Crime, Drama",8.9,96.0,A jury holdout attempts to prevent a miscarria...,"Director: Sidney Lumet | Stars: Henry Fonda, L...","Votes: 674,629 | Gross: $4.36M"
8,8,9. Inception (2010),PG-13,148 min,"Action, Adventure, Sci-Fi",8.8,74.0,A thief who steals corporate secrets through t...,Director: Christopher Nolan | Stars: Leonardo ...,"Votes: 2,022,655 | Gross: $292.58M"
9,9,10. Fight Club (1999),R,139 min,Drama,8.8,66.0,An insomniac office worker and a devil-may-car...,"Director: David Fincher | Stars: Brad Pitt, Ed...","Votes: 1,820,268 | Gross: $37.03M"

In [22]:
df.describe()

        Unnamed: 0         Rate   Metascore
count  1000.000000  1000.000000  712.000000
mean    499.500000     8.097500   81.001404
std     288.819436     0.169566    9.811801
min       0.000000     8.000000   61.000000
25%     249.750000     8.000000   73.000000
50%     499.500000     8.000000   82.000000
75%     749.250000     8.100000   88.250000
max     999.000000     9.300000  100.000000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   Title        1000 non-null   object
 2   Certificate  973 non-null    object
 3   Duration     1000 non-null   object
 4   Genre        1000 non-null   object
 5   Rate         1000 non-null   float64
 6   Metascore    712 non-null    float64
 7   Description  1000 non-null   object
 8   Cast         1000 non-null   object
 9   Info         1000 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 78.3+ KB

In [24]:
df.isnull().sum()

Unnamed: 0       0
Title            0
Certificate     27
Duration         0
Genre            0
Rate             0
Metascore      288
Description      0
Cast             0
Info             0
dtype: int64

In [25]:
df.dtypes

Unnamed: 0       int64
Title           object
Certificate     object
Duration        object
Genre           object
Rate           float64
Metascore      float64
Description     object
Cast            object
Info            object
dtype: object

In [26]:
df.columns

Index(['Unnamed: 0', 'Title', 'Certificate', 'Duration', 'Genre', 'Rate',
       'Metascore', 'Description', 'Cast', 'Info'],
      dtype='object')

In [27]:
df= df[['No_of_Votes','Series_Title','Overview','Genre']]
df

KeyError: "['No_of_Votes', 'Series_Title', 'Overview'] not in index"

In [31]:
df["tags"]= df['Overview']+df['Genre']
df

KeyError: 'Overview'

In [33]:
new_data = df.drop(columns=['Overview','Genre'])
new_data

KeyError: "['Overview'] not found in axis"

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv= CountVectorizer(max_features=10000, stop_words="english")
cv

In [ ]:
vector=cv.fit_transform(new_data["tags"].values.astype("U")).toarray()

vector.shape

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity=cosine_similarity(vector)
similarity

In [ ]:
new_data[new_data['Series_Title']== 'The Godfather'].index[0]

In [ ]:
distance= sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance [0:5]:
     print(new_data.iloc[i[0]].Series_Title)

In [ ]:
def recommand(movies):
    index=new_data[new_data["Series_Title"]==movies].index[0]
    distance= sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
    for i in distance [0:5]:
         print(new_data.iloc[i[0]].Series_Title)

In [ ]:
recommand('The Godfather')

In [ ]:
import pickle
pickle.dump(new_data, open('movies_list.pkl','wb'))

In [ ]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [ ]:
pickle.load(open('movies_list.pkl','rb'))